apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-webapp-deployment
  labels:
    app: petstore-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petstore-webapp
  template:
    metadata:
      labels:
        app: petstore-webapp
    spec:
      containers:
        - name: petstore-webapp
          image: alendoc/java-petstore:v1
          stdin: true
          tty: true
          ports:
            - containerPort: 6868
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SPRING_APPLICATION_JSON
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-webapp-service
spec:
  type: NodePort
  selector:
    app: petstore-webapp
  ports:
    - protocol: TCP
      port: 6868
      targetPort: 6868
      nodePort: 30009
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalance-service
spec:
  selector:
    app: petstore-webapp
  ports:
    - port: 6868
  externalTrafficPolicy: Local
  type: LoadBalancer