apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  MYSQLDB_USER: cm9vdA==
  MYSQLDB_ROOT_PASSWORD: cGV0U3RvcmUx
  MYSQLDB_DATABASE: cGV0c3RvcmU=
  GOOGLE_OAUTH2_ID: NTQ0NjQwMDM5MzItOGhrdmFmODlza3Axa3RmMXVlMXFuNGcyMGVqdTdwMTYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  GOOGLE_OAUTH2_SECRET: R09DU1BYLUVEbEVCelRDUUJRbWVEMTJEZXdhazJyQTdPVmg=
  SPRING_APPLICATION_JSON: eyAic3ByaW5nLmRhdGFzb3VyY2UudXJsIiA6ICJqZGJjOm15c3FsOi8vbXlzcWwtc2VydmljZTozMzA2L3BldHN0b3JlIiwgInNwcmluZy5kYXRhc291cmNlLnVzZXJuYW1lIiA6ICJyb290IiwgInNwcmluZy5kYXRhc291cmNlLnBhc3N3b3JkIiA6ICJwZXRTdG9yZTEiLCAic3ByaW5nLmpwYS5oaWJlcm5hdGUuZGRsLWF1dG8iIDogInVwZGF0ZSIsICJzcHJpbmcuanBhLmRlZmVyLWRhdGFzb3VyY2UtaW5pdGlhbGl6YXRpb24iIDogInRydWUiLCAic3ByaW5nLnNxbC5pbml0Lm1vZGUiIDogImFsd2F5cyIsICJzcHJpbmcuc2VjdXJpdHkub2F1dGgyLmNsaWVudC5yZWdpc3RyYXRpb24uZ29vZ2xlLmNsaWVudC1pZCIgOiAiNTQ0NjQwMDM5MzItOGhrdmFmODlza3Axa3RmMXVlMXFuNGcyMGVqdTdwMTYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCAic3ByaW5nLnNlY3VyaXR5Lm9hdXRoMi5jbGllbnQucmVnaXN0cmF0aW9uLmdvb2dsZS5jbGllbnQtc2VjcmV0IiA6ICJHT0NTUFgtRURsRUJ6VENRQlFtZUQxMkRld2FrMnJBN09WaCIsICJzcHJpbmcuanBhLnByb3BlcnRpZXMuaGliZXJuYXRlLmRpYWxlY3QiIDogIm9yZy5oaWJlcm5hdGUuZGlhbGVjdC5NeVNRTDhEaWFsZWN0IiB9